### ISSUE TITLE
Error when running in an iframe with different domain

### ISSUE THREAD

**Issue by jlee0831** [rackt/history#198] opened 2016-01-05 22:48 UTC
We've received a few tracked errors when users are trying to translate our site using google. 

Do you have any recommendations for how to deal with history changes when running in an iframe?

**Comment by taurose** [comment] 2016-01-06 00:10
Do you use `useBasename`?

**Comment by aaronjensen** [comment] 2016-01-06 00:13
answering for @jlee0831, no we do not.

**Comment by aaronjensen** [comment] 2016-01-06 03:54
@taurose is it something that would help with this problem or were you thinking it was something that may have caused it?

**Comment by taurose** [comment] 2016-01-06 19:10
I was hoping it would be the cause. 

After taking a closer look, it seems like the translate service wasn't designed with single page apps in mind. It's not just that they use iframes from a different domain, but they also proxy the actual page, i.e. the iframe looks something like `<iframe src="http://translate.google.com/....?url=originalpage.com">`, which also breaks ajax requests (cross origin).

Links that are part of the initial HTML are rewritten to fit their schema, but dynamically inserted ones are not and will navigate the iframe to your real page without any translation features. Also, it looks like the translations don't even work with dynamic content.

So I don't think there's an easy solution to this. One thing you could do is use server-side rendering so that google actually gets some content it can translate. You could probably avoid the history error on startup by checking  `location` and then use hash or memory history. But you'd still run into the problem of inserted content/links. And I imagine client-side React will complain due to the HTML having been modified by google (and then revert their changes). Plus, you still couldn't do AJAX.

So here's some ideas:

* if you just want to get rid of the error but don't need the translation to work, check `window.location` for the presence of google translate (or the absence of your domain - not sure if that's a good idea though), and then tell users that google translate isn't supported or something
* if you want the translation to work, use server-side rendering so that all your content can be accessed without javascript, and then do a check like above to not run react and react-router at all so your page works like a static one

**Comment by aaronjensen** [comment] 2016-01-07 01:32
Thanks for looking into this, @taurose, please feel free to close it out. @jlee0831 could you edit your comment to remove or anonymize the link so that we don't get more errors triggered unnecessarily? Thanks :smile:

**Comment by taurose** [comment] 2016-01-07 02:55
Sure thing!

**Closed by taurose** 2016-01-07 02:55 UTC
