### ISSUE TITLE
Prevent duplicate consecutive pushStates

### ISSUE THREAD

**Issue by AndrewIngram** [rackt/history#105] opened 2015-10-15 15:39 UTC
(Originally opened against react-router: https://github.com/rackt/react-router/issues/2281)

If I click a link twice in succession (mainly possible if transitions are blocked until data is ready), both clicks push the new history entry, so that when I use the back button I also need to click it twice.

The expected behaviour (for me) is to prevent pushState from having an effect if the new URL and state are already in the history.

**Comment by taurose** [comment] 2015-10-23 23:00
Sounds like this could be solved with #43 ? Although it wouldn't prevent the second transition, it would make it a replace instead of a push, fixing the back button behavior you mentioned.

**Comment by taion** [comment] 2015-10-23 23:09
Good point! Should we close this issue as a dupe of #43 then?

**Comment by mjackson** [comment] 2015-10-25 16:56
@AndrewIngram I assume you're using hash history? If so, we should close this as a dup of #43.

**Closed** 2015-10-25 17:51 UTC
Labels: duplicate
