### ISSUE TITLE
Location state lost when going back on iOS safari

### ISSUE THREAD

**Issue by chrisbianca** [rackt/history#145] opened 2015-11-19 15:33 UTC
I'm making use of location state to allow me to support modals in my react-router powered application.

However, I've noticed that when navigating backwards, and for that matter forwards, with iOS Safari the state stored for the location is lost.  This happens whether using the back or forward buttons, or programatically using history.go(n).

This same code works fine on desktop browsers, and on Android browsers, so looks to be restricted to iOS Safari.

I'm not sure whether it's something going wrong in the History module or a bug in iOS itself.  Any ideas?

**Comment by chrisbianca** [comment] 2015-11-19 16:18
Having investigated a bit further, it seems that this issue was caused by running iOS Safari in private browsing mode.

It looks like this is true of desktop Safari and the Android browsers too: http://caniuse.com/#search=sessionstorage (known issue 3).

I'll leave this issue open in case you wanted to take a look at different ways of working when running in private mode.  Feel free to close if it's not something you wish to support.

**Comment by taion** [comment] 2015-11-19 16:27
In that case it's just a dupe of https://github.com/rackt/history/issues/123, then - we can continue discussion there.

**Closed by taion** 2015-11-19 16:27 UTC
